# Maven
- task: loadiumIntegration@1
  inputs:
    access_key: 'byA1U3RDtQYKGNOyXlFv'
    secret_key: 'LBbqqFECYcwWW59G2MMUxTHBuwgYME9L96Lqkrla'
    test_key: '21khf08oc7q30p2sg02ilnc9gl65c8hk'
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
