# Maven


trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: loadiumIntegration@1
  inputs:
    access_key: '6sAqxQLP6ov57VwPoAfM'
    secret_key: 'dz3Ya5Kd8ro4GKNzwp3BKE9GNVMmUmDa2iw55279'
    createTest: true
    test_name: 'My New Test-Caglar'
    testType: 'JMX'
    jmeter_version: '5.0'
    region: 'eu-west-1'
    file_path: '$(System.DefaultWorkingDirectory)/dummy.jmx'
    additionalFile: false
    split: false
    engine: '1'
    thread: '50'
    duration: '2'
    iteration: '-1'
    rampup: '10'  


