# Maven



trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: loadiumIntegration@1
  inputs:
    access_key: 'LcnkXXaJsUl1BJ1oMB1E'
    secret_key: '0ECXALlsMWOgqqXv0h3Cz1mql5qJxMyfeuHN2Y4I'
    createTest: true
    test_name: 'My New Test Caglar'
    testType: 'JMX'
    jmeter_version: '5.0'
    region: 'eu-west-1'
    file_path: '$(System.DefaultWorkingDirectory)/REPLACE_WITH_FILE_NAME'
    additionalFile: false
    engine: '1'
    thread: '20'
    duration: '2'
    iteration: '-1'
    rampup: '10'