# Maven



trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: loadiumIntegration@1
  inputs:
    access_key: 'qExpaCZBXEfj3BapXhTY'
    secret_key: 'NaejNmEH0x0Otd4Zfg4tdy6Zup1JJidDR2mPcuxv'
    createTest: true
    test_name: 'My New Test Azure Test Caglar 7'
    testType: 'JMX'
    jmeter_version: '5.4.3'
    region: 'eu-west-1'
    file_path: '$(System.DefaultWorkingDirectory)/dummy.jmx'
    additionalFile: false
    engine: '1'
    thread: '20'
    duration: '2'
    iteration: '-1'
    rampup: '10'